// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-EP8y1AXSLjTMUy0Fgn9KMtDWG7lqiow',
    appId: '1:952167676532:web:660df19c761c110017af21',
    messagingSenderId: '952167676532',
    projectId: 'algorithm-visualization-7ee9c',
    authDomain: 'algorithm-visualization-7ee9c.firebaseapp.com',
    storageBucket: 'algorithm-visualization-7ee9c.firebasestorage.app',
    measurementId: 'G-1B3T8RNYBL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDwLTjPnupVcxE-14CgKKfOjcQZXpKQiY',
    appId: '1:952167676532:android:62ac2ea528848a0517af21',
    messagingSenderId: '952167676532',
    projectId: 'algorithm-visualization-7ee9c',
    storageBucket: 'algorithm-visualization-7ee9c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoA145y63I5I78VFxPANNaaPIz3o3XO1Y',
    appId: '1:952167676532:ios:0b70c6580c7fa4a117af21',
    messagingSenderId: '952167676532',
    projectId: 'algorithm-visualization-7ee9c',
    storageBucket: 'algorithm-visualization-7ee9c.firebasestorage.app',
    iosBundleId: 'com.example.algorithmVisualizer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-EP8y1AXSLjTMUy0Fgn9KMtDWG7lqiow',
    appId: '1:952167676532:web:1dca6e812832ad4d17af21',
    messagingSenderId: '952167676532',
    projectId: 'algorithm-visualization-7ee9c',
    authDomain: 'algorithm-visualization-7ee9c.firebaseapp.com',
    storageBucket: 'algorithm-visualization-7ee9c.firebasestorage.app',
    measurementId: 'G-822NJDMXJQ',
  );
}
